### ISSUE TITLE
[FEAT] Allow integration tests using EE version

### ISSUE THREAD

**Issue by damienwebdev** [extdn/github-actions-m2#42] opened 2021-10-12 01:46 UTC

**Comment by damienwebdev** [comment] 2022-02-22 20:06
This was originally addressed by #48 but is not reverted by 6f754f357439912489376b54ae4df52e4dc6c591 and 4885780b85b01e0e1b0920c54ea7b21e48b76550

I don't really understand why there are 3 different variables for $MAGENTO_PROJECT_NAME ($PROJECT_NAME, $INPUT_PROJECT_NAME)

```bash
INPUT_PROJECT_NAME="magento/project-enterprise-edition" && MAGENTO_PROJECT_NAME=""
test -z "${MAGENTO_PROJECT_NAME}" || MAGENTO_PROJECT_NAME=$INPUT_PROJECT_NAME
test -z "$MAGENTO_PROJECT_NAME" && MAGENTO_PROJECT_NAME="magento/project-community-edition"
echo $MAGENTO_PROJECT_NAME
```

**Comment by jissereitsma** [comment] 2022-02-26 13:13
Yes and no. By using `env` it works for me. By using `with` it does not work for me. Which YAML are you using?

**Comment by damienwebdev** [comment] 2022-02-26 19:22
```yml
  steps:
      - uses: actions/checkout@v2
      - name: M2 Integration Tests with Magento 2 (Php7.4)
        uses: extdn/github-actions-m2/magento-integration-tests/7.4
        with:
          module_name: MyPackage
          composer_name: namespace/package
          ce_version: '2.4.3'
          project_name: magento/project-enterprise-edition
        env:
          REPOSITORY_URL: https://repo.magento.com/
          COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}
```

**Comment by jissereitsma** [comment] 2022-02-27 08:53
Ok, in my own trials there is also an `env` with name `PROJECT_NAME` set. But the variable structure is indeed bad, to say the least. Let me get into a fix.

**Comment by jissereitsma** [comment] 2022-02-27 09:08
Like this: https://github.com/extdn/github-actions-m2/commit/6ad270bb659b7bc28947f4e523c02d6a33260500 Let me know if this fixes things for you.

**Comment by piotrkwiecinski** [comment] 2022-12-29 18:35
I can confirm that using PROJECT_NAME works with EE version

**Comment by jissereitsma** [comment] 2023-01-11 18:24
I'm going to close this issue, because I've gotten various reports now that this was solved correctly (even though I suspect @damienwebdev is no longer using this specific solution ;))

**Closed by jissereitsma** 2023-01-11 18:24 UTC

**Comment by damienwebdev** [comment] 2023-01-12 18:57
@jissereitsma yes, confirming this works, sorry for never closing the issue.
