### ISSUE TITLE
Cannot use PHP 7.4 action for coding standards

### ISSUE THREAD

**Issue by schmengler** [extdn/github-actions-m2#43] opened 2021-10-25 16:56 UTC
I'm trying to use PHP 7.4 for the coding standards action with the following yml file

```
 name: ExtDN M2 Coding Standard
 on:
   push:
     branches:
       - master
   pull_request:
 
 jobs:
   static:
     name: M2 Coding Standard
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - uses: extdn/github-actions-m2/magento-coding-standard/7.4@master
```

Which errors with:
```
Pull down action image 'extdn/magento-coding-standard-action:7.4-latest'
  /usr/bin/docker pull extdn/magento-coding-standard-action:7.4-latest
  Error response from daemon: manifest for extdn/magento-coding-standard-action:7.4-latest not found: manifest unknown: manifest unknown
  Warning: Docker pull failed with exit code 1, back off 9.014 seconds before retry.
  /usr/bin/docker pull extdn/magento-coding-standard-action:7.4-latest
  Error response from daemon: manifest for extdn/magento-coding-standard-action:7.4-latest not found: manifest unknown: manifest unknown
  Warning: Docker pull failed with exit code 1, back off 8.851 seconds before retry.
  /usr/bin/docker pull extdn/magento-coding-standard-action:7.4-latest
  Error response from daemon: manifest for extdn/magento-coding-standard-action:7.4-latest not found: manifest unknown: manifest unknown
Error: Docker pull failed with exit code 1
``` 

(without `/7.4` it works but cannot parse PHP 7.4 syntax obviously)

**Comment by torhoehn** [comment] 2021-11-23 20:45
Just discovered the same issue.

**Comment by jissereitsma** [comment] 2021-12-01 15:04
Reopening the issue, because the PR was merged but the issue is not fixed yet.

**Comment by jissereitsma** [comment] 2021-12-16 13:35
Could you retest this? It should be working now.

**Comment by torhoehn** [comment] 2021-12-20 18:35
@jissereitsma Looks good for me now, thank you!

**Comment by jissereitsma** [comment] 2021-12-21 08:47
I'm closing this issue as of yet, because we have 2 reports that this is working now. Let me know if this is not working for you.

**Closed by jissereitsma** 2021-12-21 08:47 UTC
